targets:
    linux:
        - name: debian-stretch
          platform: debian
          platform_version: stretch
          family: debian
        - name: ubuntu-xenial
          platform: ubuntu
          platform_version: xenial
          family: debian
        - name: ubuntu-bionic
          platform: ubuntu
          platform_version: bionic
          family: debian
        - name: centos-7
          platform: centos
          platform_version: 7
          family: redhat

    macos:
        - name: macos-10.14
          platform: macos
          platform_version: 10.14
          family: macos
