name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: ["nightly-build"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [
          debian-stretch,
          ubuntu-xenial,
          centos-7,
        ]
        include:
          - target: debian-stretch
            platform: debian
            platform_version: stretch
          - target: ubuntu-xenial
            platform: ubuntu
            platform_version: xenial
          - target: centos-7
            platform: centos
            platform_version: 7

    steps:

    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/debian-stretch@master
      if: matrix.target == 'debian-stretch'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/debian-stretch@master
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/ubuntu-xenial@master
      if: matrix.target == 'ubuntu-xenial'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/ubuntu-xenial@master
      if: matrix.target == 'ubuntu-xenial'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/centos-7@master
      if: matrix.target == 'centos-7'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/centos-7@master
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"


    - uses: actions/upload-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

  build-macos:
    runs-on: macos-10.14

    strategy:
      max-parallel: 4
      matrix:
        target: [
          macos-10.14,
        ]
        include:
          - target: macos-10.14
            platform: macos
            platform_version: 10.14

    steps:
    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb/edgedb-pkg

    - name: Build (${{ matrix.target }})
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
      run: |
        edgedb-pkg/integration/macos/build.sh

    - name: Test (${{ matrix.target }})
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
      run: |
        edgedb-pkg/integration/macos/test.sh

    - uses: actions/upload-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

  publish-linux:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [
          debian-stretch,
          ubuntu-xenial,
          centos-7,
        ]
        include:
          - target: debian-stretch
            platform: debian
            platform_version: stretch
          - target: ubuntu-xenial
            platform: ubuntu
            platform_version: xenial
          - target: centos-7
            platform: centos
            platform_version: 7

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: "${{ matrix.target }}"

    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/debian@master
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/debian-stretch@master
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/debian@master
      if: matrix.target == 'ubuntu-xenial'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/ubuntu-xenial@master
      if: matrix.target == 'ubuntu-xenial'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/redhat@master
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/centos-7@master
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"


    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-docker
        ref: master
        path: edgedb/dockerfile

    - name: Publish Docker Image (${{ matrix.target }})
      uses: elgohr/Publish-Docker-Github-Action@2.6
      if: matrix.target == 'debian-stretch'
      with:
        name: edgedb/edgedb:nightly
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        workdir: dockerfile
        buildargs: version=${{ steps.describe.outputs.version-slot }},subdist=.nightly

  publish-macos:
    needs: [build-linux, build-macos]
    runs-on: macos-10.14
    strategy:
      max-parallel: 4
      matrix:
        target: [
          macos-10.14,
        ]
        include:
          - target: macos-10.14
            platform: macos
            platform_version: 10.14

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb/edgedb-pkg

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: "${{ matrix.target }}"

    - name: Publish (${{ matrix.target }})
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
      run: |
        edgedb-pkg/integration/macos/publish.sh

